import type { Bien } from "@/lib/types";

export const biens: Bien[] = [
  {
    id: "baobab-3b",
    nom: "Résidence Baobab — Appt 3B",
    type: "appartement",
    adresse: "12 Rue des Almadies",
    quartier: "Almadies",
    ville: "Dakar",
    loyerMensuelFcfa: 85000,
    statutOccupation: "occupe",
    locataireId: "fatou-ndiaye",
    dateAjout: "2025-02-10",
  },
  {
    id: "baobab-1a",
    nom: "Résidence Baobab — Appt 1A",
    type: "appartement",
    adresse: "12 Rue des Almadies",
    quartier: "Almadies",
    ville: "Dakar",
    loyerMensuelFcfa: 65000,
    statutOccupation: "occupe",
    locataireId: "moussa-sarr",
    dateAjout: "2025-02-10",
  },
  {
    id: "cite-fleurs-12",
    nom: "Cité Fleurs — Villa 12",
    type: "villa",
    adresse: "Rue des Jardins, Lot 12",
    quartier: "Cocody",
    ville: "Abidjan",
    loyerMensuelFcfa: 140000,
    statutOccupation: "occupe",
    locataireId: "yves-kouassi",
    dateAjout: "2025-06-01",
  },
  {
    id: "bonanjo-studio",
    nom: "Studio Bonanjo",
    type: "studio",
    adresse: "Avenue de la Liberté",
    quartier: "Bonanjo",
    ville: "Douala",
    loyerMensuelFcfa: 45000,
    statutOccupation: "occupe",
    locataireId: "chantal-mbarga",
    dateAjout: "2025-09-14",
  },
  {
    id: "akwa-2c",
    nom: "Immeuble Akwa — Appt 2C",
    type: "appartement",
    adresse: "Boulevard de la Liberté",
    quartier: "Akwa",
    ville: "Douala",
    loyerMensuelFcfa: 92000,
    statutOccupation: "occupe",
    locataireId: "paul-mvondo",
    dateAjout: "2024-11-20",
  },
  {
    id: "fidjrosse-villa",
    nom: "Villa Fidjrossè",
    type: "villa",
    adresse: "Rue 412",
    quartier: "Fidjrossè",
    ville: "Cotonou",
    loyerMensuelFcfa: 110000,
    statutOccupation: "vacant",
    dateAjout: "2026-06-02",
  },
];
