import type { Paiement } from "@/lib/types";

export const paiements: Paiement[] = [
  {
    id: "pay-baobab-3b-08",
    bienId: "baobab-3b",
    locataireId: "fatou-ndiaye",
    periode: "2026-08",
    montantFcfa: 85000,
    methode: "mobile-money",
    statut: "recu",
    datePaiement: "2026-08-03",
  },
  {
    id: "pay-baobab-1a-08",
    bienId: "baobab-1a",
    locataireId: "moussa-sarr",
    periode: "2026-08",
    montantFcfa: 65000,
    methode: "mobile-money",
    statut: "en-attente",
  },
  {
    id: "pay-cite-fleurs-12-08",
    bienId: "cite-fleurs-12",
    locataireId: "yves-kouassi",
    periode: "2026-08",
    montantFcfa: 140000,
    methode: "virement",
    statut: "recu",
    datePaiement: "2026-08-05",
  },
  {
    id: "pay-bonanjo-studio-08",
    bienId: "bonanjo-studio",
    locataireId: "chantal-mbarga",
    periode: "2026-08",
    montantFcfa: 45000,
    methode: "especes",
    statut: "en-attente",
  },
  {
    id: "pay-akwa-2c-08",
    bienId: "akwa-2c",
    locataireId: "paul-mvondo",
    periode: "2026-08",
    montantFcfa: 92000,
    methode: "mobile-money",
    statut: "recu",
    datePaiement: "2026-08-02",
  },
  {
    id: "pay-baobab-3b-07",
    bienId: "baobab-3b",
    locataireId: "fatou-ndiaye",
    periode: "2026-07",
    montantFcfa: 85000,
    methode: "mobile-money",
    statut: "recu",
    datePaiement: "2026-07-02",
  },
  {
    id: "pay-baobab-1a-07",
    bienId: "baobab-1a",
    locataireId: "moussa-sarr",
    periode: "2026-07",
    montantFcfa: 65000,
    methode: "mobile-money",
    statut: "recu",
    datePaiement: "2026-07-04",
  },
];
